create table if not exists public.jobs (
 id bigint generated by default as identity primary key,
 doctor text not null, patient text not null, type text not null default 'Sur dent',
 work_in timestamptz, due timestamptz, ceramic_due timestamptz, ceramic_in timestamptz,
 control_in timestamptz, department text not null default 'Céramique',
 issue text, status text not null default 'En cours',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.job_history (
 id bigint generated by default as identity primary key,
 job_id bigint references public.jobs(id) on delete cascade,
 patient text, action text, changes text, created_at timestamptz not null default now()
);
alter table public.jobs replica identity full;
alter table public.job_history replica identity full;
do $$ begin
 alter publication supabase_realtime add table public.jobs;
exception when duplicate_object then null; end $$;
alter table public.jobs enable row level security;
alter table public.job_history enable row level security;
drop policy if exists "pd jobs read" on public.jobs;
drop policy if exists "pd jobs insert" on public.jobs;
drop policy if exists "pd jobs update" on public.jobs;
drop policy if exists "pd jobs delete" on public.jobs;
drop policy if exists "pd history read" on public.job_history;
drop policy if exists "pd history insert" on public.job_history;
create policy "pd jobs read" on public.jobs for select using (true);
create policy "pd jobs insert" on public.jobs for insert with check (true);
create policy "pd jobs update" on public.jobs for update using (true) with check (true);
create policy "pd jobs delete" on public.jobs for delete using (true);
create policy "pd history read" on public.job_history for select using (true);
create policy "pd history insert" on public.job_history for insert with check (true);
